# Copyright 2010 Michael Murr
#
# This file is part of LibForensics.
#
# LibForensics is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LibForensics is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with LibForensics.  If not, see <http://www.gnu.org/licenses/>.

"""Constants for working with Windows network provider types"""

__docformat__ = "restructuredtext en"
__all__ = [
    "WNNC_NET_MSNET", "WNNC_NET_LANMAN", "WNNC_NET_NETWARE", "WNNC_NET_VINES",
    "WNNC_NET_10NET", "WNNC_NET_LOCUS", "WNNC_NET_SUN_PC_NFS",
    "WNNC_NET_LANSTEP", "WNNC_NET_9TILES", "WNNC_NET_LANTASTIC",
    "WNNC_NET_AS400", "WNNC_NET_FTP_NFS", "WNNC_NET_PATHWORKS",
    "WNNC_NET_LIFENET", "WNNC_NET_POWERLAN", "WNNC_NET_BWNFS",
    "WNNC_NET_COGENT", "WNNC_NET_FARALLON", "WNNC_NET_APPLETALK",
    "WNNC_NET_INTERGRAPH", "WNNC_NET_SYMFONET", "WNNC_NET_CLEARCASE",
    "WNNC_NET_FRONTIER", "WNNC_NET_BMC", "WNNC_NET_DCE", "WNNC_NET_AVID",
    "WNNC_NET_DOCUSPACE", "WNNC_NET_MANGOSOFT", "WNNC_NET_SERNET",
    "WNNC_NET_RIVERFRONT1", "WNNC_NET_RIVERFRONT2", "WNNC_NET_DECORB",
    "WNNC_NET_PROTSTOR", "WNNC_NET_FJ_REDIR", "WNNC_NET_DISTINCT",
    "WNNC_NET_TWINS", "WNNC_NET_RDR2SAMPLE", "WNNC_NET_CSC", "WNNC_NET_3IN1",
    "WNNC_NET_EXTENDNET", "WNNC_NET_STAC", "WNNC_NET_FOXBAT", "WNNC_NET_YAHOO",
    "WNNC_NET_EXIFS", "WNNC_NET_DAV", "WNNC_NET_KNOWARE",
    "WNNC_NET_OBJECT_DIRE", "WNNC_NET_MASFAX", "WNNC_NET_HOB_NFS",
    "WNNC_NET_SHIVA", "WNNC_NET_IBMAL", "WNNC_NET_LOCK", "WNNC_NET_TERMSRV",
    "WNNC_NET_SRT", "WNNC_NET_QUINCY", "WNNC_NET_OPENAFS", "WNNC_NET_AVID1",
    "WNNC_NET_DFS", "WNNC_NET_KWNP", "WNNC_NET_ZENWORKS",
    "WNNC_NET_DRIVEONWEB", "WNNC_NET_VMWARE", "WNNC_NET_RSFX",
    "WNNC_NET_MFILES", "WNNC_NET_MS_NFS", "WNNC_NET_GOOGLE",
    "wnnc_net_names"
]

WNNC_NET_MSNET = 0x10000
WNNC_NET_LANMAN = 0x20000
WNNC_NET_NETWARE = 0x30000
WNNC_NET_VINES = 0x40000
WNNC_NET_10NET = 0x50000
WNNC_NET_LOCUS = 0x60000
WNNC_NET_SUN_PC_NFS = 0x70000
WNNC_NET_LANSTEP = 0x80000
WNNC_NET_9TILES = 0x90000
WNNC_NET_LANTASTIC = 0xA0000
WNNC_NET_AS400 = 0xB0000
WNNC_NET_FTP_NFS = 0xC0000
WNNC_NET_PATHWORKS = 0xD0000
WNNC_NET_LIFENET = 0xE0000
WNNC_NET_POWERLAN = 0xF0000
WNNC_NET_BWNFS = 0x100000
WNNC_NET_COGENT = 0x110000
WNNC_NET_FARALLON = 0x120000
WNNC_NET_APPLETALK = 0x130000
WNNC_NET_INTERGRAPH = 0x140000
WNNC_NET_SYMFONET = 0x150000
WNNC_NET_CLEARCASE = 0x160000
WNNC_NET_FRONTIER = 0x170000
WNNC_NET_BMC = 0x180000
WNNC_NET_DCE = 0x190000
WNNC_NET_AVID = 0x1A0000
WNNC_NET_DOCUSPACE = 0x1B0000
WNNC_NET_MANGOSOFT = 0x1C0000
WNNC_NET_SERNET = 0x1D0000
WNNC_NET_RIVERFRONT1 = 0x1E0000
WNNC_NET_RIVERFRONT2 = 0x1F0000
WNNC_NET_DECORB = 0x200000
WNNC_NET_PROTSTOR = 0x210000
WNNC_NET_FJ_REDIR = 0x220000
WNNC_NET_DISTINCT = 0x230000
WNNC_NET_TWINS = 0x240000
WNNC_NET_RDR2SAMPLE = 0x250000
WNNC_NET_CSC = 0x260000
WNNC_NET_3IN1 = 0x270000
WNNC_NET_EXTENDNET = 0x290000
WNNC_NET_STAC = 0x2A0000
WNNC_NET_FOXBAT = 0x2B0000
WNNC_NET_YAHOO = 0x2C0000
WNNC_NET_EXIFS = 0x2D0000
WNNC_NET_DAV = 0x2E0000
WNNC_NET_KNOWARE = 0x2F0000
WNNC_NET_OBJECT_DIRE = 0x300000
WNNC_NET_MASFAX = 0x310000
WNNC_NET_HOB_NFS = 0x320000
WNNC_NET_SHIVA = 0x330000
WNNC_NET_IBMAL = 0x340000
WNNC_NET_LOCK = 0x350000
WNNC_NET_TERMSRV = 0x360000
WNNC_NET_SRT = 0x370000
WNNC_NET_QUINCY = 0x380000
WNNC_NET_OPENAFS = 0x390000
WNNC_NET_AVID1 = 0x3A0000
WNNC_NET_DFS = 0x3B0000
WNNC_NET_KWNP = 0x3C0000
WNNC_NET_ZENWORKS = 0x3D0000
WNNC_NET_DRIVEONWEB = 0x3E0000
WNNC_NET_VMWARE = 0x3F0000
WNNC_NET_RSFX = 0x400000
WNNC_NET_MFILES = 0x410000
WNNC_NET_MS_NFS = 0x420000
WNNC_NET_GOOGLE = 0x430000

wnnc_net_names = {
    WNNC_NET_10NET: "WNNC_NET_10NET",
    WNNC_NET_3IN1: "WNNC_NET_3IN1",
    WNNC_NET_9TILES: "WNNC_NET_9TILES",
    WNNC_NET_APPLETALK: "WNNC_NET_APPLETALK",
    WNNC_NET_AS400: "WNNC_NET_AS400",
    WNNC_NET_AVID: "WNNC_NET_AVID",
    WNNC_NET_AVID1: "WNNC_NET_AVID1",
    WNNC_NET_BMC: "WNNC_NET_BMC",
    WNNC_NET_BWNFS: "WNNC_NET_BWNFS",
    WNNC_NET_CLEARCASE: "WNNC_NET_CLEARCASE",
    WNNC_NET_COGENT: "WNNC_NET_COGENT",
    WNNC_NET_CSC: "WNNC_NET_CSC",
    WNNC_NET_DAV: "WNNC_NET_DAV",
    WNNC_NET_DCE: "WNNC_NET_DCE",
    WNNC_NET_DECORB: "WNNC_NET_DECORB",
    WNNC_NET_DFS: "WNNC_NET_DFS",
    WNNC_NET_DISTINCT: "WNNC_NET_DISTINCT",
    WNNC_NET_DOCUSPACE: "WNNC_NET_DOCUSPACE",
    WNNC_NET_DRIVEONWEB: "WNNC_NET_DRIVEONWEB",
    WNNC_NET_EXIFS: "WNNC_NET_EXIFS",
    WNNC_NET_EXTENDNET: "WNNC_NET_EXTENDNET",
    WNNC_NET_FARALLON: "WNNC_NET_FARALLON",
    WNNC_NET_FJ_REDIR: "WNNC_NET_FJ_REDIR",
    WNNC_NET_FOXBAT: "WNNC_NET_FOXBAT",
    WNNC_NET_FRONTIER: "WNNC_NET_FRONTIER",
    WNNC_NET_FTP_NFS: "WNNC_NET_FTP_NFS",
    WNNC_NET_GOOGLE: "WNNC_NET_GOOGLE",
    WNNC_NET_HOB_NFS: "WNNC_NET_HOB_NFS",
    WNNC_NET_IBMAL: "WNNC_NET_IBMAL",
    WNNC_NET_INTERGRAPH: "WNNC_NET_INTERGRAPH",
    WNNC_NET_KNOWARE: "WNNC_NET_KNOWARE",
    WNNC_NET_KWNP: "WNNC_NET_KWNP",
    WNNC_NET_LANMAN: "WNNC_NET_LANMAN",
    WNNC_NET_LANSTEP: "WNNC_NET_LANSTEP",
    WNNC_NET_LANTASTIC: "WNNC_NET_LANTASTIC",
    WNNC_NET_LIFENET: "WNNC_NET_LIFENET",
    WNNC_NET_LOCK: "WNNC_NET_LOCK",
    WNNC_NET_LOCUS: "WNNC_NET_LOCUS",
    WNNC_NET_MANGOSOFT: "WNNC_NET_MANGOSOFT",
    WNNC_NET_MASFAX: "WNNC_NET_MASFAX",
    WNNC_NET_MFILES: "WNNC_NET_MFILES",
    WNNC_NET_MSNET: "WNNC_NET_MSNET",
    WNNC_NET_MS_NFS: "WNNC_NET_MS_NFS",
    WNNC_NET_NETWARE: "WNNC_NET_NETWARE",
    WNNC_NET_OBJECT_DIRE: "WNNC_NET_OBJECT_DIRE",
    WNNC_NET_OPENAFS: "WNNC_NET_OPENAFS",
    WNNC_NET_PATHWORKS: "WNNC_NET_PATHWORKS",
    WNNC_NET_POWERLAN: "WNNC_NET_POWERLAN",
    WNNC_NET_PROTSTOR: "WNNC_NET_PROTSTOR",
    WNNC_NET_QUINCY: "WNNC_NET_QUINCY",
    WNNC_NET_RDR2SAMPLE: "WNNC_NET_RDR2SAMPLE",
    WNNC_NET_RIVERFRONT1: "WNNC_NET_RIVERFRONT1",
    WNNC_NET_RIVERFRONT2: "WNNC_NET_RIVERFRONT2",
    WNNC_NET_RSFX: "WNNC_NET_RSFX",
    WNNC_NET_SERNET: "WNNC_NET_SERNET",
    WNNC_NET_SHIVA: "WNNC_NET_SHIVA",
    WNNC_NET_SRT: "WNNC_NET_SRT",
    WNNC_NET_STAC: "WNNC_NET_STAC",
    WNNC_NET_SUN_PC_NFS: "WNNC_NET_SUN_PC_NFS",
    WNNC_NET_SYMFONET: "WNNC_NET_SYMFONET",
    WNNC_NET_TERMSRV: "WNNC_NET_TERMSRV",
    WNNC_NET_TWINS: "WNNC_NET_TWINS",
    WNNC_NET_VINES: "WNNC_NET_VINES",
    WNNC_NET_VMWARE: "WNNC_NET_VMWARE",
    WNNC_NET_YAHOO: "WNNC_NET_YAHOO",
    WNNC_NET_ZENWORKS: "WNNC_NET_ZENWORKS"
}
