# Copyright 2009 Michael Murr
#
# This file is part of LibForensics.
#
# LibForensics is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LibForensics is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with LibForensics.  If not, see <http://www.gnu.org/licenses/>.

"""
Structures for Microsoft Word documents.

.. moduleauthor:: Michael Murr (mmurr@codeforensics.net)
"""

__docformat__ = "restructuredtext en"
__all__ = [
    "FcLcb", "FcPgdOld", "FcPgd", "FibHeader", "FibShorts", "FibLongs",
    "Fib", "FibFcLcb97", "FibFcLcb2000", "FibFcLcb2002", "FibFcLcb2003",
    "FibFcLcb2007", "FibCswNewData2000", "FibCswNewData2007",

    "FNIF"
]

from lf.struct.datastruct import DataStruct_LE
from lf.struct.datatype import Bytes

from lf.windows.structs import FILETIME
from lf.windows.types import (
    LONG, ULONG, USHORT, UINT8, UINT16, UINT32, UINT64, INT32
)

class FcLcb(DataStruct_LE):
    fields = [
        ULONG("fc"),
        ULONG("lcb")
    ]
# end class FIBFCLCB

class FcPgdOld(DataStruct_LE):
    fields = [
        FcLcb("pgd"),
        FcLcb("bkd")
    ]
# end class FcPgdOld

class FcPgd(DataStruct_LE):
    fields = [
        FcLcb("pgd"),
        FcLcb("bkd"),
        FcLcb("afd")
    ]
# end class FcPgd

class FibHeader(DataStruct_LE):
    fields = [
        UINT16("wIdent"),
        UINT16("nFib"),
        UINT16("nProduct"),
        UINT16("lid"),
        UINT16("pnNext"),
        UINT8("flags1"),
        UINT8("flags2"),
        UINT16("nFibBack"),
        UINT32("lKey"),
        UINT8("envr"),
        UINT8("flags3"),
        UINT16("chs"),
        UINT16("chsTables"),
        ULONG("fcMin"),
        ULONG("fcMac"),
    ]
# end class FibHeader

class FibShorts(DataStruct_LE):
    fields = [
        USHORT("wMagicCreated"),
        USHORT("wMagicRevised"),
        USHORT("wMagicCreatedPrivate"),
        USHORT("mMagicRevisedPrivate"),
        USHORT("pnFbpChpFirst_W6"),
        USHORT("pnChpFirst_W6"),
        USHORT("cpBteChp_W6"),
        USHORT("pnFbpPapFirst_W6"),
        USHORT("pnPapFirst_W6"),
        USHORT("cpnBtePap_W6"),
        USHORT("pnFbpLvcFirst_W6"),
        USHORT("pnLvcFirst_W6"),
        USHORT("cpnBteLvc_W6"),
        USHORT("lidFE")
    ]
# end class FibShorts

class FibLongs(DataStruct_LE):
    fields = [
        LONG("cbMac"),
        ULONG("lProductCreated"),
        ULONG("lProductRevised"),
        LONG("ccpText"),
        LONG("ccpFtn"),
        LONG("ccpHdd"),
        LONG("ccpMcr"),
        LONG("ccpAtn"),
        LONG("ccpEdn"),
        LONG("ccpTxbx"),
        LONG("ccpHdrTxbx"),
        LONG("pnFbpChpFirst"),
        LONG("pnChpFirst"),
        LONG("cpnBteChp"),
        LONG("pnFbpBapFirst"),
        LONG("pnPapFirst"),
        LONG("cpnBtePap"),
        LONG("pnFbpLvcFirst"),
        LONG("pnLvcFirst"),
        LONG("cpnBteLvc"),
        LONG("fcIslandFirst"),
        LONG("fcIslandLim")
    ]
# end class FibLongs

class Fib(DataStruct_LE):
    fields = [
        FibHeader("header"),
        UINT16("csw"),
    ]
# end class Fib

class FibFcLcb97(DataStruct_LE):
    fields = [
        FcLcb("stshOrig"),
        FcLcb("stshF"),
        FcLcb("plcfFndRef"),
        FcLcb("plcfFndTxt"),
        FcLcb("plcfAndRef"),
        FcLcb("plcfAndTxt"),
        FcLcb("plcfSed"),
        FcLcb("plcPad"),
        FcLcb("plcfPhe"),
        FcLcb("sttbfGlsy"),
        FcLcb("plcfGlsy"),
        FcLcb("plcfHdd"),
        FcLcb("plcfBteChpx"),
        FcLcb("plcfBtePapx"),
        FcLcb("plcfSea"),
        FcLcb("sttbfFfn"),
        FcLcb("plcfFldMom"),
        FcLcb("plcfFldHdr"),
        FcLcb("plcfFldFtn"),
        FcLcb("plcfFldAtn"),
        FcLcb("plcfFldMcr"),
        FcLcb("sttbfBkmk"),
        FcLcb("plcfBkf"),
        FcLcb("plcfBkl"),
        FcLcb("cmds"),
        FcLcb("plcMcr"),
        FcLcb("sttbfMcr"),
        FcLcb("prDrvr"),
        FcLcb("prEnvPort"),
        FcLcb("prEnvLand"),
        FcLcb("wss"),
        FcLcb("dop"),
        FcLcb("sttbfAssoc"),
        FcLcb("clx"),
        FcLcb("plcfPgdFtn"),
        FcLcb("autosaveSource"),
        FcLcb("GrpXstAtnOwner"),
        FcLcb("sttbfAtnBkmk"),
        FcLcb("plcDoaMom"),
        FcLcb("plcDoaHdr"),
        FcLcb("plcSpaMom"),
        FcLcb("plcSpaHdr"),
        FcLcb("plcfAtnBkf"),
        FcLcb("plcfAtnBkl"),
        FcLcb("pms"),
        FcLcb("formFldSttbs"),
        FcLcb("plcfEndRef"),
        FcLcb("plcfEndTxt"),
        FcLcb("plcfFldEdn"),
        FcLcb("plcfPgdEdn"),
        FcLcb("dggInfo"),
        FcLcb("sttbfRMark"),
        FcLcb("sttbCaption"),
        FcLcb("sttbAutoCaption"),
        FcLcb("plcfWkb"),
        FcLcb("plcfSpl"),
        FcLcb("plcfTxbxTxt"),
        FcLcb("plcfFldTxbx"),
        FcLcb("plcfHdrTxbxTxt"),
        FcLcb("plcfFldHdrTxbx"),
        FcLcb("stwUser"),
        FcLcb("sttbTtmbd"),
        FcLcb("cookieData"),
        FcPgdOld("pgdMotherOldOld"),
        FcPgdOld("pgdFtnOldOld"),
        FcPgdOld("pgdEndOldOld"),
        FcLcb("sttbfIntlFld"),
        FcLcb("routeSlip"),
        FcLcb("sttbSavedBy"),
        FcLcb("sttbFnm"),
        FcLcb("plcfLst"),
        FcLcb("plcfLfo"),
        FcLcb("plcfTxbxBkd"),
        FcLcb("plcfTxbxHdrBkd"),
        FcLcb("docUndoWord9"),
        FcLcb("rgbUse"),
        FcLcb("usp"),
        FcLcb("uskf"),
        FcLcb("plcupcRgbUse"),
        FcLcb("plcupcUsp"),
        FcLcb("sttbGlsyStyle"),
        FcLcb("plgOsl"),
        FcLcb("plcOcx"),
        FcLcb("plcfBteLvc"),
        FILETIME("modified"),
        FcLcb("plcfLvcPre10"),
        FcLcb("plcAsumy"),
        FcLcb("plcfGram"),
        FcLcb("sttbListNames"),
        FcLcb("sttbfUssr"),
    ]
# end class FibFcLcb97

class FibFcLcb2000(DataStruct_LE):
    fields = [
        FcLcb("stshOrig"),
        FcLcb("stshF"),
        FcLcb("plcfFndRef"),
        FcLcb("plcfFndTxt"),
        FcLcb("plcfAndRef"),
        FcLcb("plcfAndTxt"),
        FcLcb("plcfSed"),
        FcLcb("plcPad"),
        FcLcb("plcfPhe"),
        FcLcb("sttbfGlsy"),
        FcLcb("plcfGlsy"),
        FcLcb("plcfHdd"),
        FcLcb("plcfBteChpx"),
        FcLcb("plcfBtePapx"),
        FcLcb("plcfSea"),
        FcLcb("sttbfFfn"),
        FcLcb("plcfFldMom"),
        FcLcb("plcfFldHdr"),
        FcLcb("plcfFldFtn"),
        FcLcb("plcfFldAtn"),
        FcLcb("plcfFldMcr"),
        FcLcb("sttbfBkmk"),
        FcLcb("plcfBkf"),
        FcLcb("plcfBkl"),
        FcLcb("cmds"),
        FcLcb("plcMcr"),
        FcLcb("sttbfMcr"),
        FcLcb("prDrvr"),
        FcLcb("prEnvPort"),
        FcLcb("prEnvLand"),
        FcLcb("wss"),
        FcLcb("dop"),
        FcLcb("sttbfAssoc"),
        FcLcb("clx"),
        FcLcb("plcfPgdFtn"),
        FcLcb("autosaveSource"),
        FcLcb("GrpXstAtnOwner"),
        FcLcb("sttbfAtnBkmk"),
        FcLcb("plcDoaMom"),
        FcLcb("plcDoaHdr"),
        FcLcb("plcSpaMom"),
        FcLcb("plcSpaHdr"),
        FcLcb("plcfAtnBkf"),
        FcLcb("plcfAtnBkl"),
        FcLcb("pms"),
        FcLcb("formFldSttbs"),
        FcLcb("plcfEndRef"),
        FcLcb("plcfEndTxt"),
        FcLcb("plcfFldEdn"),
        FcLcb("plcfPgdEdn"),
        FcLcb("dggInfo"),
        FcLcb("sttbfRMark"),
        FcLcb("sttbCaption"),
        FcLcb("sttbAutoCaption"),
        FcLcb("plcfWkb"),
        FcLcb("plcfSpl"),
        FcLcb("plcfTxbxTxt"),
        FcLcb("plcfFldTxbx"),
        FcLcb("plcfHdrTxbxTxt"),
        FcLcb("plcfFldHdrTxbx"),
        FcLcb("stwUser"),
        FcLcb("sttbTtmbd"),
        FcLcb("cookieData"),
        FcPgdOld("pgdMotherOldOld"),
        FcPgdOld("pgdFtnOldOld"),
        FcPgdOld("pgdEndOldOld"),
        FcLcb("sttbfIntlFld"),
        FcLcb("routeSlip"),
        FcLcb("sttbSavedBy"),
        FcLcb("sttbFnm"),
        FcLcb("plcfLst"),
        FcLcb("plcfLfo"),
        FcLcb("plcfTxbxBkd"),
        FcLcb("plcfTxbxHdrBkd"),
        FcLcb("docUndoWord9"),
        FcLcb("rgbUse"),
        FcLcb("usp"),
        FcLcb("uskf"),
        FcLcb("plcupcRgbUse"),
        FcLcb("plcupcUsp"),
        FcLcb("sttbGlsyStyle"),
        FcLcb("plgOsl"),
        FcLcb("plcOcx"),
        FcLcb("plcfBteLvc"),
        FILETIME("modified"),
        FcLcb("plcfLvcPre10"),
        FcLcb("plcAsumy"),
        FcLcb("plcfGram"),
        FcLcb("sttbListNames"),
        FcLcb("sttbfUssr"),
        FcLcb("plcfTch"),
        FcLcb("rmdfThreading"),
        FcLcb("mid"),
        FcLcb("sttbRgtplc"),
        FcLcb("msoEnvelope"),
        FcLcb("plcfLad"),
        FcLcb("rgDofr"),
        FcLcb("plcosl"),
        FcLcb("plcfCookieOld"),
        FcPgdOld("pgdMotherOld"),
        FcPgdOld("pgdFtnOld"),
        FcPgdOld("pgdEdnOld"),
    ]
# end class FibFcLcb2000

class FibFcLcb2002(DataStruct_LE):
    fields = [
        FcLcb("stshOrig"),
        FcLcb("stshF"),
        FcLcb("plcfFndRef"),
        FcLcb("plcfFndTxt"),
        FcLcb("plcfAndRef"),
        FcLcb("plcfAndTxt"),
        FcLcb("plcfSed"),
        FcLcb("plcPad"),
        FcLcb("plcfPhe"),
        FcLcb("sttbfGlsy"),
        FcLcb("plcfGlsy"),
        FcLcb("plcfHdd"),
        FcLcb("plcfBteChpx"),
        FcLcb("plcfBtePapx"),
        FcLcb("plcfSea"),
        FcLcb("sttbfFfn"),
        FcLcb("plcfFldMom"),
        FcLcb("plcfFldHdr"),
        FcLcb("plcfFldFtn"),
        FcLcb("plcfFldAtn"),
        FcLcb("plcfFldMcr"),
        FcLcb("sttbfBkmk"),
        FcLcb("plcfBkf"),
        FcLcb("plcfBkl"),
        FcLcb("cmds"),
        FcLcb("plcMcr"),
        FcLcb("sttbfMcr"),
        FcLcb("prDrvr"),
        FcLcb("prEnvPort"),
        FcLcb("prEnvLand"),
        FcLcb("wss"),
        FcLcb("dop"),
        FcLcb("sttbfAssoc"),
        FcLcb("clx"),
        FcLcb("plcfPgdFtn"),
        FcLcb("autosaveSource"),
        FcLcb("GrpXstAtnOwner"),
        FcLcb("sttbfAtnBkmk"),
        FcLcb("plcDoaMom"),
        FcLcb("plcDoaHdr"),
        FcLcb("plcSpaMom"),
        FcLcb("plcSpaHdr"),
        FcLcb("plcfAtnBkf"),
        FcLcb("plcfAtnBkl"),
        FcLcb("pms"),
        FcLcb("formFldSttbs"),
        FcLcb("plcfEndRef"),
        FcLcb("plcfEndTxt"),
        FcLcb("plcfFldEdn"),
        FcLcb("plcfPgdEdn"),
        FcLcb("dggInfo"),
        FcLcb("sttbfRMark"),
        FcLcb("sttbCaption"),
        FcLcb("sttbAutoCaption"),
        FcLcb("plcfWkb"),
        FcLcb("plcfSpl"),
        FcLcb("plcfTxbxTxt"),
        FcLcb("plcfFldTxbx"),
        FcLcb("plcfHdrTxbxTxt"),
        FcLcb("plcfFldHdrTxbx"),
        FcLcb("stwUser"),
        FcLcb("sttbTtmbd"),
        FcLcb("cookieData"),
        FcPgdOld("pgdMotherOldOld"),
        FcPgdOld("pgdFtnOldOld"),
        FcPgdOld("pgdEndOldOld"),
        FcLcb("sttbfIntlFld"),
        FcLcb("routeSlip"),
        FcLcb("sttbSavedBy"),
        FcLcb("sttbFnm"),
        FcLcb("plcfLst"),
        FcLcb("plcfLfo"),
        FcLcb("plcfTxbxBkd"),
        FcLcb("plcfTxbxHdrBkd"),
        FcLcb("docUndoWord9"),
        FcLcb("rgbUse"),
        FcLcb("usp"),
        FcLcb("uskf"),
        FcLcb("plcupcRgbUse"),
        FcLcb("plcupcUsp"),
        FcLcb("sttbGlsyStyle"),
        FcLcb("plgOsl"),
        FcLcb("plcOcx"),
        FcLcb("plcfBteLvc"),
        FILETIME("modified"),
        FcLcb("plcfLvcPre10"),
        FcLcb("plcAsumy"),
        FcLcb("plcfGram"),
        FcLcb("sttbListNames"),
        FcLcb("sttbfUssr"),
        FcLcb("plcfTch"),
        FcLcb("rmdfThreading"),
        FcLcb("mid"),
        FcLcb("sttbRgtplc"),
        FcLcb("msoEnvelope"),
        FcLcb("plcfLad"),
        FcLcb("rgDofr"),
        FcLcb("plcosl"),
        FcLcb("plcfCookieOld"),
        FcPgdOld("pgdMotherOld"),
        FcPgdOld("pgdFtnOld"),
        FcPgdOld("pgdEdnOld"),
        FcLcb("unused"),
        FcLcb("plcfPgp"),
        FcLcb("plcfUim"),
        FcLcb("plfGuidUim"),
        FcLcb("attrdExtra"),
        FcLcb("plrsid"),
        FcLcb("sttbfBkmkFactoid"),
        FcLcb("plcfBkfFactoid"),
        FcLcb("plcfCookie"),
        FcLcb("plcfBklFactoid"),
        FcLcb("factoidData"),
        FcLcb("docUndo"),
        FcLcb("sttbfBkmkFcc"),
        FcLcb("plcfBkfFcc"),
        FcLcb("plcfBklFcc"),
        FcLcb("sttbfBkmkBPRepairs"),
        FcLcb("plcfBkfBPRepairs"),
        FcLcb("plcfBklBPRepairs"),
        FcLcb("pmsNew"),
        FcLcb("odso"),
        FcLcb("plcfPmiOldXP"),
        FcLcb("plcfPmiNewXP"),
        FcLcb("plcfPmiMixedXp"),
        FcLcb("encryptedProps"),
        FcLcb("plcfFactoid"),
        FcLcb("plcfLvcOldXP"),
        FcLcb("plcfLvcNewXP"),
        FcLcb("plcfLvcMixedXP")
    ]
# end class FibFcLcb2002

class FibFcLcb2003(DataStruct_LE):
    fields = [
        FcLcb("stshOrig"),
        FcLcb("stshF"),
        FcLcb("plcfFndRef"),
        FcLcb("plcfFndTxt"),
        FcLcb("plcfAndRef"),
        FcLcb("plcfAndTxt"),
        FcLcb("plcfSed"),
        FcLcb("plcPad"),
        FcLcb("plcfPhe"),
        FcLcb("sttbfGlsy"),
        FcLcb("plcfGlsy"),
        FcLcb("plcfHdd"),
        FcLcb("plcfBteChpx"),
        FcLcb("plcfBtePapx"),
        FcLcb("plcfSea"),
        FcLcb("sttbfFfn"),
        FcLcb("plcfFldMom"),
        FcLcb("plcfFldHdr"),
        FcLcb("plcfFldFtn"),
        FcLcb("plcfFldAtn"),
        FcLcb("plcfFldMcr"),
        FcLcb("sttbfBkmk"),
        FcLcb("plcfBkf"),
        FcLcb("plcfBkl"),
        FcLcb("cmds"),
        FcLcb("plcMcr"),
        FcLcb("sttbfMcr"),
        FcLcb("prDrvr"),
        FcLcb("prEnvPort"),
        FcLcb("prEnvLand"),
        FcLcb("wss"),
        FcLcb("dop"),
        FcLcb("sttbfAssoc"),
        FcLcb("clx"),
        FcLcb("plcfPgdFtn"),
        FcLcb("autosaveSource"),
        FcLcb("GrpXstAtnOwner"),
        FcLcb("sttbfAtnBkmk"),
        FcLcb("plcDoaMom"),
        FcLcb("plcDoaHdr"),
        FcLcb("plcSpaMom"),
        FcLcb("plcSpaHdr"),
        FcLcb("plcfAtnBkf"),
        FcLcb("plcfAtnBkl"),
        FcLcb("pms"),
        FcLcb("formFldSttbs"),
        FcLcb("plcfEndRef"),
        FcLcb("plcfEndTxt"),
        FcLcb("plcfFldEdn"),
        FcLcb("plcfPgdEdn"),
        FcLcb("dggInfo"),
        FcLcb("sttbfRMark"),
        FcLcb("sttbCaption"),
        FcLcb("sttbAutoCaption"),
        FcLcb("plcfWkb"),
        FcLcb("plcfSpl"),
        FcLcb("plcfTxbxTxt"),
        FcLcb("plcfFldTxbx"),
        FcLcb("plcfHdrTxbxTxt"),
        FcLcb("plcfFldHdrTxbx"),
        FcLcb("stwUser"),
        FcLcb("sttbTtmbd"),
        FcLcb("cookieData"),
        FcPgdOld("pgdMotherOldOld"),
        FcPgdOld("pgdFtnOldOld"),
        FcPgdOld("pgdEndOldOld"),
        FcLcb("sttbfIntlFld"),
        FcLcb("routeSlip"),
        FcLcb("sttbSavedBy"),
        FcLcb("sttbFnm"),
        FcLcb("plcfLst"),
        FcLcb("plcfLfo"),
        FcLcb("plcfTxbxBkd"),
        FcLcb("plcfTxbxHdrBkd"),
        FcLcb("docUndoWord9"),
        FcLcb("rgbUse"),
        FcLcb("usp"),
        FcLcb("uskf"),
        FcLcb("plcupcRgbUse"),
        FcLcb("plcupcUsp"),
        FcLcb("sttbGlsyStyle"),
        FcLcb("plgOsl"),
        FcLcb("plcOcx"),
        FcLcb("plcfBteLvc"),
        FILETIME("modified"),
        FcLcb("plcfLvcPre10"),
        FcLcb("plcAsumy"),
        FcLcb("plcfGram"),
        FcLcb("sttbListNames"),
        FcLcb("sttbfUssr"),
        FcLcb("plcfTch"),
        FcLcb("rmdfThreading"),
        FcLcb("mid"),
        FcLcb("sttbRgtplc"),
        FcLcb("msoEnvelope"),
        FcLcb("plcfLad"),
        FcLcb("rgDofr"),
        FcLcb("plcosl"),
        FcLcb("plcfCookieOld"),
        FcPgdOld("pgdMotherOld"),
        FcPgdOld("pgdFtnOld"),
        FcPgdOld("pgdEdnOld"),
        FcLcb("unused"),
        FcLcb("plcfPgp"),
        FcLcb("plcfUim"),
        FcLcb("plfGuidUim"),
        FcLcb("attrdExtra"),
        FcLcb("plrsid"),
        FcLcb("sttbfBkmkFactoid"),
        FcLcb("plcfBkfFactoid"),
        FcLcb("plcfCookie"),
        FcLcb("plcfBklFactoid"),
        FcLcb("factoidData"),
        FcLcb("docUndo"),
        FcLcb("sttbfBkmkFcc"),
        FcLcb("plcfBkfFcc"),
        FcLcb("plcfBklFcc"),
        FcLcb("sttbfBkmkBPRepairs"),
        FcLcb("plcfBkfBPRepairs"),
        FcLcb("plcfBklBPRepairs"),
        FcLcb("pmsNew"),
        FcLcb("odso"),
        FcLcb("plcfPmiOldXP"),
        FcLcb("plcfPmiNewXP"),
        FcLcb("plcfPmiMixedXp"),
        FcLcb("encryptedProps"),
        FcLcb("plcfFactoid"),
        FcLcb("plcfLvcOldXP"),
        FcLcb("plcfLvcNewXP"),
        FcLcb("plcfLvcMixedXP"),
        FcLcb("hplXsdr"),
        FcLcb("sttbBkmkSdt"),
        FcLcb("plcfBkfSdt"),
        FcLcb("plcfBklSdt"),
        FcLcb("customXForm"),
        FcLcb("sttbfBkmkProt"),
        FcLcb("plcfBkfProt"),
        FcLcb("plcfBklProt"),
        FcLcb("sttbProtUser"),
        FcLcb("plcftpc"),
        FcLcb("plcfPmiOld"),
        FcLcb("plcfPmiOldInline"),
        FcLcb("plcfPmiNew"),
        FcLcb("plcfPnewNewInline"),
        FcLcb("plcfLvcOld"),
        FcLcb("plcfLvcOldInline"),
        FcLcb("plcfLvcNew"),
        FcLcb("plcfLvcNewInline"),
        FcPgd("pgdMother"),
        FcPgd("pgdFtn"),
        FcPgd("pgdEdn"),
        FcLcb("afd"),
    ]
# end class FibFcLcb2003

class FibFcLcb2007(DataStruct_LE):
    fields = [
        FcLcb("stshOrig"),
        FcLcb("stshF"),
        FcLcb("plcfFndRef"),
        FcLcb("plcfFndTxt"),
        FcLcb("plcfAndRef"),
        FcLcb("plcfAndTxt"),
        FcLcb("plcfSed"),
        FcLcb("plcPad"),
        FcLcb("plcfPhe"),
        FcLcb("sttbfGlsy"),
        FcLcb("plcfGlsy"),
        FcLcb("plcfHdd"),
        FcLcb("plcfBteChpx"),
        FcLcb("plcfBtePapx"),
        FcLcb("plcfSea"),
        FcLcb("sttbfFfn"),
        FcLcb("plcfFldMom"),
        FcLcb("plcfFldHdr"),
        FcLcb("plcfFldFtn"),
        FcLcb("plcfFldAtn"),
        FcLcb("plcfFldMcr"),
        FcLcb("sttbfBkmk"),
        FcLcb("plcfBkf"),
        FcLcb("plcfBkl"),
        FcLcb("cmds"),
        FcLcb("plcMcr"),
        FcLcb("sttbfMcr"),
        FcLcb("prDrvr"),
        FcLcb("prEnvPort"),
        FcLcb("prEnvLand"),
        FcLcb("wss"),
        FcLcb("dop"),
        FcLcb("sttbfAssoc"),
        FcLcb("clx"),
        FcLcb("plcfPgdFtn"),
        FcLcb("autosaveSource"),
        FcLcb("GrpXstAtnOwner"),
        FcLcb("sttbfAtnBkmk"),
        FcLcb("plcDoaMom"),
        FcLcb("plcDoaHdr"),
        FcLcb("plcSpaMom"),
        FcLcb("plcSpaHdr"),
        FcLcb("plcfAtnBkf"),
        FcLcb("plcfAtnBkl"),
        FcLcb("pms"),
        FcLcb("formFldSttbs"),
        FcLcb("plcfEndRef"),
        FcLcb("plcfEndTxt"),
        FcLcb("plcfFldEdn"),
        FcLcb("plcfPgdEdn"),
        FcLcb("dggInfo"),
        FcLcb("sttbfRMark"),
        FcLcb("sttbCaption"),
        FcLcb("sttbAutoCaption"),
        FcLcb("plcfWkb"),
        FcLcb("plcfSpl"),
        FcLcb("plcfTxbxTxt"),
        FcLcb("plcfFldTxbx"),
        FcLcb("plcfHdrTxbxTxt"),
        FcLcb("plcfFldHdrTxbx"),
        FcLcb("stwUser"),
        FcLcb("sttbTtmbd"),
        FcLcb("cookieData"),
        FcPgdOld("pgdMotherOldOld"),
        FcPgdOld("pgdFtnOldOld"),
        FcPgdOld("pgdEndOldOld"),
        FcLcb("sttbfIntlFld"),
        FcLcb("routeSlip"),
        FcLcb("sttbSavedBy"),
        FcLcb("sttbFnm"),
        FcLcb("plcfLst"),
        FcLcb("plcfLfo"),
        FcLcb("plcfTxbxBkd"),
        FcLcb("plcfTxbxHdrBkd"),
        FcLcb("docUndoWord9"),
        FcLcb("rgbUse"),
        FcLcb("usp"),
        FcLcb("uskf"),
        FcLcb("plcupcRgbUse"),
        FcLcb("plcupcUsp"),
        FcLcb("sttbGlsyStyle"),
        FcLcb("plgOsl"),
        FcLcb("plcOcx"),
        FcLcb("plcfBteLvc"),
        FILETIME("modified"),
        FcLcb("plcfLvcPre10"),
        FcLcb("plcAsumy"),
        FcLcb("plcfGram"),
        FcLcb("sttbListNames"),
        FcLcb("sttbfUssr"),
        FcLcb("plcfTch"),
        FcLcb("rmdfThreading"),
        FcLcb("mid"),
        FcLcb("sttbRgtplc"),
        FcLcb("msoEnvelope"),
        FcLcb("plcfLad"),
        FcLcb("rgDofr"),
        FcLcb("plcosl"),
        FcLcb("plcfCookieOld"),
        FcPgdOld("pgdMotherOld"),
        FcPgdOld("pgdFtnOld"),
        FcPgdOld("pgdEdnOld"),
        FcLcb("unused"),
        FcLcb("plcfPgp"),
        FcLcb("plcfUim"),
        FcLcb("plfGuidUim"),
        FcLcb("attrdExtra"),
        FcLcb("plrsid"),
        FcLcb("sttbfBkmkFactoid"),
        FcLcb("plcfBkfFactoid"),
        FcLcb("plcfCookie"),
        FcLcb("plcfBklFactoid"),
        FcLcb("factoidData"),
        FcLcb("docUndo"),
        FcLcb("sttbfBkmkFcc"),
        FcLcb("plcfBkfFcc"),
        FcLcb("plcfBklFcc"),
        FcLcb("sttbfBkmkBPRepairs"),
        FcLcb("plcfBkfBPRepairs"),
        FcLcb("plcfBklBPRepairs"),
        FcLcb("pmsNew"),
        FcLcb("odso"),
        FcLcb("plcfPmiOldXP"),
        FcLcb("plcfPmiNewXP"),
        FcLcb("plcfPmiMixedXp"),
        FcLcb("encryptedProps"),
        FcLcb("plcfFactoid"),
        FcLcb("plcfLvcOldXP"),
        FcLcb("plcfLvcNewXP"),
        FcLcb("plcfLvcMixedXP"),
        FcLcb("hplXsdr"),
        FcLcb("sttbBkmkSdt"),
        FcLcb("plcfBkfSdt"),
        FcLcb("plcfBklSdt"),
        FcLcb("customXForm"),
        FcLcb("sttbfBkmkProt"),
        FcLcb("plcfBkfProt"),
        FcLcb("plcfBklProt"),
        FcLcb("sttbProtUser"),
        FcLcb("plcftpc"),
        FcLcb("plcfPmiOld"),
        FcLcb("plcfPmiOldInline"),
        FcLcb("plcfPmiNew"),
        FcLcb("plcfPnewNewInline"),
        FcLcb("plcfLvcOld"),
        FcLcb("plcfLvcOldInline"),
        FcLcb("plcfLvcNew"),
        FcLcb("plcfLvcNewInline"),
        FcPgd("pgdMother"),
        FcPgd("pgdFtn"),
        FcPgd("pgdEdn"),
        FcLcb("afd"),
        FcLcb("plcfMthd"),
        FcLcb("sttbfBkmkMoveFrom"),
        FcLcb("plcfBkfMoveFrom"),
        FcLcb("plcfBklMoveFrom"),
        FcLcb("sttbfBkmkMoveTo"),
        FcLcb("plcfBkfMoveTo"),
        FcLcb("plcfBklMoveTo"),
        FcLcb("unused1"),
        FcLcb("unused2"),
        FcLcb("unused3"),
        FcLcb("sttbfBkmkArto"),
        FcLcb("plcfBkfArto"),
        FcLcb("plcfBklArto"),
        FcLcb("artoData"),
        FcLcb("unused4"),
        FcLcb("unused5"),
        FcLcb("unused6"),
        FcLcb("ossTheme"),
        FcLcb("colorSchemeMapping")
    ]
# end class FibFcLcb2007

class FibCswNewData2000(DataStruct_LE):
    fields = [
        UINT16("quickSavesNew")
    ]
# end class FibCswNewData2000

class FibCswNewData2007(DataStruct_LE):
    fields = [
        UINT16("quickSavesNew"),
        UINT16("lidThemeOther"),
        UINT16("lidThemeFE"),
        UINT16("lidThemeCS")
    ]
# end class FibCswNewData2007

class FNIF(DataStruct_LE):
    fields = [
        UINT16("fnpi"),
        UINT8("ichRelative"),
        UINT8("fnfb"),
        Bytes(4, "unused")
    ]
# end class FNIF
